Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
Documentation:
  Enabled: false
Security/Eval:
  Enabled: false
Metrics/LineLength:
  Max: 140
  Enabled: false
Metrics/MethodLength:
  Max: 5
  Enabled: false
Metrics/ClassLength:
  Max: 150
Metrics/ParameterLists:
  Max: 4
Rails/FindEach:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/HashSyntax:
  Exclude:
   - lib/tasks/*
Style/PredicateName:
  NamePrefixBlacklist:
   - is_
Style/AndOr:
  EnforcedStyle: conditionals
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Style/BlockDelimiters:
  EnforcedStyle: semantic
  Exclude:
   - factories/**/*
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Exclude:
   - spec/**/*
   - lib/tasks/*
   - config/routes.rb
Metrics/AbcSize:
  Max: 10
